In [1]:
import pandas as pd
DF=pd.DataFrame()
print(DF)

print("------------------slide 8----------------------")

df=pd.DataFrame([11,22,33,44,55])
print(df)

print("-------------------slide 9,10---------------------")
daf = pd.DataFrame([11,22,33,44,55],index=['R1','R2','R3','R4','R5'],
                   columns=['C1'])
print(daf)

print("-------------------slide 11---------------------")
data=pd.DataFrame([[21,'X','A'],[32,'IX','A'],[23,'X','A'],[12,'XI','A']])
print(data)

print("-------------------slide 12---------------------")
dataf=pd.DataFrame([[21,'X','A'],[32,'IX','A'],[23,'X','A'],[12,'XI','A']],
                   index=['rec1','rec2','rec3','rec4'],columns=["rno","class","sec"])
print(dataf)

print("-------------------slide 13---------------------")
Df=pd.DataFrame({'rno':[21,28,31],'class':['IX','X','XI'],'sec':['B','A','C']})
print(Df)

print("-------------------slide 14---------------------")
dF=pd.DataFrame({'B_id':['B1','B8','B5'],'Sub':['Hindi','Math','Science'],
                 'Cost':[450,520,400]},index=['R1','R2','R3'])
print(dF)

print("-------------------slide 15,16---------------------")
datafr=pd.DataFrame([{'Ram':25,'Anil':29,'Simple':28},
                     {'Ram':21,'Anil':25,'Simple':23},
                     {'Ram':23,'Anil':18}],
                     index=['Term1','Term2','Term3'])
print(datafr)
print("-------------------slide 17,18,19,20---------------------")
s1=pd.Series([10,20,30,40])
s2=pd.Series([11,22,33,44])
s3=pd.Series([34,44,54,])
dframe=pd.DataFrame([s1,s2,s3],index=['r1','r2','r3'])
print(dframe)
print("-------------------slide 21,22,23,24,25---------------------")
import numpy as np
ar1=np.array([1,2,3,4])
ar2=np.array([10,20,30,40])
ar3=np.array([-23,-43,67,90])
DATAf=pd.DataFrame([ar1,ar2,ar3])
print(DATAf)
print("-----------------slide 26,27(adding column)-------------------")
dataFR=pd.DataFrame([{'Ram':25,'Anil':29,'Simple':28},
                     {'Ram':21,'Anil':25,'Simple':23},
                     {'Ram':23,'Anil':18,'Simple':26}],
                     index=['R1','R2','R3'])
print(dataFR)
dataFR['Amit']=[18,22,25]
print(dataFR)
dataFR['Parth']=[28,12,30]
print(dataFR)
print("-----------------slide 28,29(adding row)-------------------")
dataFrame=pd.DataFrame([{'Ram':25,'Anil':29,'Simple':28},
                     {'Ram':21,'Anil':25,'Simple':23},
                     {'Ram':23,'Anil':18,'Simple':26}],
                     index=['R1','R2','R3'])
print(dataFrame)
dataFrame.loc['R4']=[18,22,25]
print(dataFrame)
print("-----------------slide 30,31,(deleting row)-------------------")
dataFRAME=pd.DataFrame([{'Ram':25,'Anil':29,'Simple':28},
                     {'Ram':21,'Anil':25,'Simple':23},
                     {'Ram':23,'Anil':18,'Simple':26}],
                     index=['R1','R2','R3'])
print(dataFRAME)
print("------------------------")
dataFRAME=dataFRAME.drop(['R2','R1'],axis=0)
print(dataFRAME)
print("-----------------slide 32,33,34(deleting columns)-------------------")
dataFRAM=pd.DataFrame([{'Ram':25,'Anil':29,'Simple':28},
                     {'Ram':21,'Anil':25,'Simple':23},
                     {'Ram':23,'Anil':18,'Simple':26}],
                     index=['R1','R2','R3'])
print(dataFRAM)
print("------------------------")
print(dataFRAM.drop(['Simple','Ram'],axis=1))
print(dataFRAM)
print("-----------------slide 35,36(renaming row)-------------------")
dataFRA=pd.DataFrame([{'Ram':25,'Anil':29,'Simple':28},
                     {'Ram':21,'Anil':25,'Simple':23},
                     {'Ram':23,'Anil':18,'Simple':26}],
                     index=['R1','R2','R3'])
print(dataFRA)
dataFRA=dataFRA.rename({'R1':'Maths','R2':'Science','R3':'English'},
                       axis='index')
print("------------------------")
print(dataFRA)
print("-----------------slide 37,38(renaming column)-------------------")
dataFR=pd.DataFrame([{'Ram':25,'Anil':29,'Simple':28},
                     {'Ram':21,'Anil':25,'Simple':23},
                     {'Ram':23,'Anil':18,'Simple':26}],
                     index=['R1','R2','R3'])
print(dataFR)
dataFR=dataFR.rename({'Ram':'Ravi','Simple':'Sumit'},axis='columns')
print("------------------------")
print(dataFR)
print("-----------------slide 39,40-------------------")
datA=pd.DataFrame([[25,29,28],[21,25,23],[23,18,26]],
                  index=['R1','R2','R3'],
                  columns=['Ram','Anil','Simple'])
print(datA)
print("------------------------")
print(datA.loc[['R1','R3']])
print("-----------------slide 41-------------------")
daTA=pd.DataFrame([[25,29,28],[21,25,23],[23,18,26]],
                  index=['R1','R2','R3'],
                  columns=['Ram','Anil','Simple'])
print(daTA)
print("------------------------")
print(daTA['Ram'])
print("-----------------slide 42-------------------")
dATA=pd.DataFrame([[25,29,28],[21,25,23],[23,18,26]],
                  index=['R1','R2','R3'],
                  columns=['Ram','Anil','Simple'])
print(dATA)
print("------------------------")
print(dATA[['Ram','Anil']])
print("-----------------slide 43-------------------")
dATAF=pd.DataFrame([[25,29,28],[21,25,23],[23,18,26]],
                  index=['R1','R2','R3'],
                  columns=['Ram','Anil','Simple'])
print(dATAF)
print("------------------------")
print(dATAF.loc[:,'Ram'])
print("-----------------slide 44-------------------")
dATAFR=pd.DataFrame([[25,29,28],[21,25,23],[23,18,26]],
                  index=['R1','R2','R3'],
                  columns=['Ram','Anil','Simple'])
print(dATAFR)
print("------------------------")
print(dATAFR.loc[:,'Ram':'Anil'])
print("-----------------slide 45-------------------")
dATAFRA=pd.DataFrame([[25,29,28],[21,25,23],[23,18,26]],
                     index=['R1','R2','R3'],
                     columns=['Ram','Anil','Simple'])
print(dATAFRA)
print("---------------------")
print(dATAFRA.iloc[:, 0:1])
print("-----------------slide 46,47-------------------")
DATAFRA=pd.DataFrame([[25,29,28],[21,25,23],[23,18,26]],
                     index=['R1','R2','R3'],
                     columns=['Ram','Anil','Simple'])
print(DATAFRA)
print("---------------------")
print(DATAFRA.iloc[:, 1:2])
print("-----------------slide 48,49-------------------")
DATAFRAM=pd.DataFrame([[25,29,28,17],[21,25,23,20],[23,18,26,23],
                       [20,18,30,15]],
                     index=['R1','R2','R3','R4'],
                     columns=['Ram','Anil','Simple','Anuj'])
print(DATAFRAM)
print("---------------------")
print(DATAFRAM.loc[['R1','R2','R4']])
print("-----------------slide 50,51,52-------------------")
DATAFRAME=pd.DataFrame([[25,29,28,17],[21,25,23,20],[23,18,26,23],
                       [20,18,30,15]],
                     index=['Math','English','Science','Hindi'],
                     columns=['Ram','Anil','Simple','Anuj'])
print(DATAFRAME)
print("---------------------")
print(DATAFRAME.loc['Math':'Science',['Ram','Anil','Anuj']])
print("-----------------slide 53,54-------------------")
DATAFRAMe=pd.DataFrame([[25,29,28],[21,25,23],[23,18,26],
                       ],
                     index=['Math','English','Science'],
                     columns=['Ram','Anil','Simple'])
print(DATAFRAMe)
print("---------------------")
print(DATAFRAMe.loc[:, 'Anil']>25)
print("-----------------slide 55,58-------------------")
df1 = pd.DataFrame(
    [[25, 29, 28, 17], [21, 25, 23, 20], [23, 18, 26, 23], [20, 18, 30, 15], [12, 15, 20, 3], [23, 12, 16, 30]],
    index=['R1', 'R2', 'R3', 'R4', 'R5', 'R6'],
    columns=['Ram', 'Anil', 'Simple', 'Anuj']
)
print(df1)
print("------------------------------------------")
df2 = pd.DataFrame(
    [[10, 12, 8, 7], [1, 5, 3, 2], [2, 1, 2, 2], [0, 1, 3, 5]],
    index=['R1', 'R2', 'R5', 'R6'],
    columns=['Ram', 'Anil', 'Ravi', 'Ashish']
)
print(df2)
print("------------------------------------------")
df1 = df1._append(df2,sort=True)
print(df1)

print("-----------------slide 59-------------------")
import pandas as pd
dframe = pd.DataFrame([[25, 29, 28, 17], [21, 25, 23, 20], [23, 18, 26, 23], [20, 18, 30, 15]], 
                  index=['R1', 'R2', 'R3', 'R4'], 
                  columns=['Ram', 'Anil', 'Simple', 'Anuj'])
print(dframe)
print("--------------------------------------------------")
print(dframe.index)
print("--------------------------------------------------")
print(dframe.columns)
print("--------------------------------------------------")
print(dframe.dtypes)
print("--------------------------------------------------")
print(dframe.shape)
print("--------------------------------------------------")
print(dframe.size)
print("--------------------------------------------------")
print(dframe.T)
print("--------------------------------------------------")
print(dframe.values)
print("--------------------------------------------------")
print(dframe.empty)
print("-----------------slide 62-------------------")
df3 = pd.DataFrame(
    [[25, 29, 28, 17], [21, 25, 23, 20], [23, 18, 26, 23], [20, 18, 30, 15], [12, 15, 20, 3], [23, 12, 16, 30]],
    index=['R1', 'R2', 'R3', 'R4', 'R5', 'R6'],
    columns=['Ram', 'Anil', 'Simple', 'Anuj']
)
print(df3)
print("------------------------------------------")
print(df3.head(2))
print("------------------------------------------")
print(df3.head(1))  
print("------------------------------------------")
print(df3.head()) 
print("------------------------------------------")
print("--------------------slide 64-------------------------")
df4 = pd.DataFrame(
    [[25, 29, 28, 17], [21, 25, 23, 20], [23, 18, 26, 23], [20, 18, 30, 15], [12, 15, 20, 3], [23, 12, 16, 30]],
    index=['R1', 'R2', 'R3', 'R4', 'R5', 'R6'],
    columns=['Ram', 'Anil', 'Simple', 'Anuj']
)
print(df4)
print("------------------------------------------")
print(df4.tail(2))
print("------------------------------------------")
print(df4.tail(1))  
print("------------------------------------------")
print(df4.tail()) 
print("------------------------------------------")

Empty DataFrame
Columns: []
Index: []
------------------slide 8----------------------
    0
0  11
1  22
2  33
3  44
4  55
-------------------slide 9,10---------------------
    C1
R1  11
R2  22
R3  33
R4  44
R5  55
-------------------slide 11---------------------
    0   1  2
0  21   X  A
1  32  IX  A
2  23   X  A
3  12  XI  A
-------------------slide 12---------------------
      rno class sec
rec1   21     X   A
rec2   32    IX   A
rec3   23     X   A
rec4   12    XI   A
-------------------slide 13---------------------
   rno class sec
0   21    IX   B
1   28     X   A
2   31    XI   C
-------------------slide 14---------------------
   B_id      Sub  Cost
R1   B1    Hindi   450
R2   B8     Math   520
R3   B5  Science   400
-------------------slide 15,16---------------------
       Ram  Anil  Simple
Term1   25    29    28.0
Term2   21    25    23.0
Term3   23    18     NaN
-------------------slide 17,18,19,20---------------------
       0     1     2     3
r1  10.0  20.0  30.0  40.0
r2  11.0  22.0  33.0  44.0
r3  34.0  44.0  54.0   NaN
-------------------slide 21,22,23,24,25---------------------
    0   1   2   3
0   1   2   3   4
1  10  20  30  40
2 -23 -43  67  90
-----------------slide 26,27(adding column)-------------------
    Ram  Anil  Simple
R1   25    29      28
R2   21    25      23
R3   23    18      26
    Ram  Anil  Simple  Amit
R1   25    29      28    18
R2   21    25      23    22
R3   23    18      26    25
    Ram  Anil  Simple  Amit  Parth
R1   25    29      28    18     28
R2   21    25      23    22     12
R3   23    18      26    25     30
-----------------slide 28,29(adding row)-------------------
    Ram  Anil  Simple
R1   25    29      28
R2   21    25      23
R3   23    18      26
    Ram  Anil  Simple
R1   25    29      28
R2   21    25      23
R3   23    18      26
R4   18    22      25
-----------------slide 30,31,(deleting row)-------------------
    Ram  Anil  Simple
R1   25    29      28
R2   21    25      23
R3   23    18      26
------------------------
    Ram  Anil  Simple
R3   23    18      26
-----------------slide 32,33,34(deleting columns)-------------------
    Ram  Anil  Simple
R1   25    29      28
R2   21    25      23
R3   23    18      26
------------------------
    Anil
R1    29
R2    25
R3    18
    Ram  Anil  Simple
R1   25    29      28
R2   21    25      23
R3   23    18      26
-----------------slide 35,36(renaming row)-------------------
    Ram  Anil  Simple
R1   25    29      28
R2   21    25      23
R3   23    18      26
------------------------
         Ram  Anil  Simple
Maths     25    29      28
Science   21    25      23
English   23    18      26
-----------------slide 37,38(renaming column)-------------------
    Ram  Anil  Simple
R1   25    29      28
R2   21    25      23
R3   23    18      26
------------------------
    Ravi  Anil  Sumit
R1    25    29     28
R2    21    25     23
R3    23    18     26
-----------------slide 39,40-------------------
    Ram  Anil  Simple
R1   25    29      28
R2   21    25      23
R3   23    18      26
------------------------
    Ram  Anil  Simple
R1   25    29      28
R3   23    18      26
-----------------slide 41-------------------
    Ram  Anil  Simple
R1   25    29      28
R2   21    25      23
R3   23    18      26
------------------------
R1    25
R2    21
R3    23
Name: Ram, dtype: int64
-----------------slide 42-------------------
    Ram  Anil  Simple
R1   25    29      28
R2   21    25      23
R3   23    18      26
------------------------
    Ram  Anil
R1   25    29
R2   21    25
R3   23    18
-----------------slide 43-------------------
    Ram  Anil  Simple
R1   25    29      28
R2   21    25      23
R3   23    18      26
------------------------
R1    25
R2    21
R3    23
Name: Ram, dtype: int64
-----------------slide 44-------------------
    Ram  Anil  Simple
R1   25    29      28
R2   21    25      23
R3   23    18      26
------------------------
    Ram  Anil
R1   25    29
R2   21    25
R3   23    18
-----------------slide 45-------------------
    Ram  Anil  Simple
R1   25    29      28
R2   21    25      23
R3   23    18      26
---------------------
    Ram
R1   25
R2   21
R3   23
-----------------slide 46,47-------------------
    Ram  Anil  Simple
R1   25    29      28
R2   21    25      23
R3   23    18      26
---------------------
    Anil
R1    29
R2    25
R3    18
-----------------slide 48,49-------------------
    Ram  Anil  Simple  Anuj
R1   25    29      28    17
R2   21    25      23    20
R3   23    18      26    23
R4   20    18      30    15
---------------------
    Ram  Anil  Simple  Anuj
R1   25    29      28    17
R2   21    25      23    20
R4   20    18      30    15
-----------------slide 50,51,52-------------------
         Ram  Anil  Simple  Anuj
Math      25    29      28    17
English   21    25      23    20
Science   23    18      26    23
Hindi     20    18      30    15
---------------------
         Ram  Anil  Anuj
Math      25    29    17
English   21    25    20
Science   23    18    23
-----------------slide 53,54-------------------
         Ram  Anil  Simple
Math      25    29      28
English   21    25      23
Science   23    18      26
---------------------
Math        True
English    False
Science    False
Name: Anil, dtype: bool
-----------------slide 55,58-------------------
    Ram  Anil  Simple  Anuj
R1   25    29      28    17
R2   21    25      23    20
R3   23    18      26    23
R4   20    18      30    15
R5   12    15      20     3
R6   23    12      16    30
------------------------------------------
    Ram  Anil  Ravi  Ashish
R1   10    12     8       7
R2    1     5     3       2
R5    2     1     2       2
R6    0     1     3       5
------------------------------------------
    Anil  Anuj  Ashish  Ram  Ravi  Simple
R1    29  17.0     NaN   25   NaN    28.0
R2    25  20.0     NaN   21   NaN    23.0
R3    18  23.0     NaN   23   NaN    26.0
R4    18  15.0     NaN   20   NaN    30.0
R5    15   3.0     NaN   12   NaN    20.0
R6    12  30.0     NaN   23   NaN    16.0
R1    12   NaN     7.0   10   8.0     NaN
R2     5   NaN     2.0    1   3.0     NaN
R5     1   NaN     2.0    2   2.0     NaN
R6     1   NaN     5.0    0   3.0     NaN
-----------------slide 59-------------------
    Ram  Anil  Simple  Anuj
R1   25    29      28    17
R2   21    25      23    20
R3   23    18      26    23
R4   20    18      30    15
--------------------------------------------------
Index(['R1', 'R2', 'R3', 'R4'], dtype='object')
--------------------------------------------------
Index(['Ram', 'Anil', 'Simple', 'Anuj'], dtype='object')
--------------------------------------------------
Ram       int64
Anil      int64
Simple    int64
Anuj      int64
dtype: object
--------------------------------------------------
(4, 4)
--------------------------------------------------
16
--------------------------------------------------
        R1  R2  R3  R4
Ram     25  21  23  20
Anil    29  25  18  18
Simple  28  23  26  30
Anuj    17  20  23  15
--------------------------------------------------
[[25 29 28 17]
 [21 25 23 20]
 [23 18 26 23]
 [20 18 30 15]]
--------------------------------------------------
False
-----------------slide 62-------------------
    Ram  Anil  Simple  Anuj
R1   25    29      28    17
R2   21    25      23    20
R3   23    18      26    23
R4   20    18      30    15
R5   12    15      20     3
R6   23    12      16    30
------------------------------------------
    Ram  Anil  Simple  Anuj
R1   25    29      28    17
R2   21    25      23    20
------------------------------------------
    Ram  Anil  Simple  Anuj
R1   25    29      28    17
------------------------------------------
    Ram  Anil  Simple  Anuj
R1   25    29      28    17
R2   21    25      23    20
R3   23    18      26    23
R4   20    18      30    15
R5   12    15      20     3
------------------------------------------
--------------------slide 64-------------------------
    Ram  Anil  Simple  Anuj
R1   25    29      28    17
R2   21    25      23    20
R3   23    18      26    23
R4   20    18      30    15
R5   12    15      20     3
R6   23    12      16    30
------------------------------------------
    Ram  Anil  Simple  Anuj
R5   12    15      20     3
R6   23    12      16    30
------------------------------------------
    Ram  Anil  Simple  Anuj
R6   23    12      16    30
------------------------------------------
    Ram  Anil  Simple  Anuj
R2   21    25      23    20
R3   23    18      26    23
R4   20    18      30    15
R5   12    15      20     3
R6   23    12      16    30
------------------------------------------